package-lock.json
package.json
tsconfig.json

Initial backend configuration:
- File structure
- Installation of initial libraries
- TS config file

initial file structure and libraries

---

frontend/src/App.tsx
frontend/src/components/Baskets/Baskets.tsx
frontend/src/components/Baskets/index.tsx

Created `Baskets` react component

Baskets component

---

backend/package.json
backend/src/main.ts
backend/src/routes/api.ts
backend/src/routes/mockApi.ts
backend/src/routes/mockBasket.ts
backend/src/types.ts

Create a mock basket endpoint for testing purposes:
Endpoints:
- Get all baskets: GET /api/mockBaskets/
- Generate random basket name: GET /api/mockBaskets/generate_name
- Create a basket: POST /api/mockBaskets/rs2geo9
- Delete basket: DELETE  /api/mockBaskets/rs2geo9
- Get requests for a basket: /api/mockBaskets/rs2geo9/requests
- Generate random basket name: DELETE /api/mockBaskets/rs2geo9/requests

Mock backend

---

frontend/src/components/Request/Request.css
frontend/src/components/Request/Request.tsx
frontend/src/components/Request/index.ts
frontend/src/types.ts

Created rough draft of the Request react component.

feat!: Request component rough draft

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/Baskets/Baskets.tsx
frontend/src/components/Nav/Nav.tsx

- react-router added to package.json
- react-router components added to frontend react components

React router

---

frontend/vite.config.ts

added '/mockApi' path to proxy

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/Baskets/Baskets.tsx
frontend/src/components/CreateBasket/CreateBasket.tsx
frontend/src/services/requestBinAPI.ts
frontend/vite.config.ts

- Implemented api service in `requestBinAPI.ts`
- api service fetches baskets and generated name from mockAPI in `App.tsx`
- `CreateBasket` component now takes and displays generated name.

Api service

---

backend/package-lock.json
backend/package.json

`ts-node-dev` added to backend dev dependencies

ts-node-dev added to backend dev dependencies

---

backend/schema.sql
backend/src/controllers/postgresql.ts

Please review schema and controller

added postgres Schema and controller

---

backend/src/controllers/mongo.ts

- added the mongo DB connection
- I wasn't sure what to call the cluster so just went with 'requestBodies' but happy to change to whatever
- Likewise with the schema I just went with 'requestBodySchema'
- also added some code to tidy up the default id property 
- note that this connecting to a test cluster so we'll need to update the database URL at some point

Mongo setup

---

backend/src/routes/mockApi.ts

The response body is now the following:
{
"basketName": "basketName"
}

CHORE: change response body when creating a basket

---

frontend/src/App.tsx
frontend/src/components/Basket/Basket.tsx
frontend/src/components/Basket/index.tsx
frontend/src/components/IndividualBasket/IndividualBasket.tsx
frontend/src/components/IndividualBasket/index.ts
frontend/src/services/requestBinAPI.ts
frontend/src/utils.ts

Basket component works with mockAPI now.
- Added `handleAPIError` utility function.
- Error handling has not been tested yet.

Basket Component State implementation

---

backend/package-lock.json
backend/package.json
backend/src/controllers/postgresql.ts
backend/src/routes/api.ts
backend/src/types.ts
backend/src/utils.ts

Added logic to generate a new basket name:
- Generate random string
- Check if name already exists in DB
- If it doesn't send new basket name as response
- If it does keep generating until finding a unique name
Added logic to generate a new token:
- Generate random token string
- Check if token already exists in DB
- If it doesn't:
- Store new token in the DB
- Send token as response
- If it does:
- Keep generating until finding a unique token

Generate name and token

---

backend/src/routes/api.ts

Add logic to get basket name from the DB

Get baskets

---

backend/src/routes/mockApi.ts

- changed the data structure as requested
- updated routes to work with the new data structure
- added the purge basket functionality on to the correct route

added basket purge

---

frontend/package-lock.json
frontend/src/components/Basket/Basket.tsx
frontend/src/components/Request/Request.tsx
frontend/src/types.ts

fix: also changed Response type b/c backend Response was changed not to include basketName

fix: Basket not displaying basketName b/c backend changes

---

frontend/src/App.tsx
frontend/src/components/CreateBasket/CreateBasket.tsx
frontend/src/services/requestBinAPI.ts

- Refactored CreateBasket component with `mui` components
- fixed `requestBinAPI.ts` to work with `basketName` mockApi change

Create basket refactor

---

frontend/src/App.tsx
frontend/src/components/Baskets/Baskets.tsx
frontend/src/components/CreateBasket/CreateBasket.tsx
frontend/src/theme.ts

Reverts dom-and-the-night-owls/requestbin#55

Revert "chore: changed Baskets UI implementing MUI"

---

backend/package.json
backend/src/main.ts

FEAT!: added ENV conditional to control which router is started

---

backend/package.json
backend/schema.sql
backend/src/controllers/postgresql.ts
backend/src/routes/api.ts
backend/src/types.ts
backend/src/utils.ts

package.json:
- added script to initialize the DB
schema.sql:
- updated schema per discussion
api.ts:
- updated the POST /baskets/:name route
- checks name uniqueness
- responds with 409 error if there is a collision
- adds name to baskets table (via utils see below)
- responds with 500 error if  something went wrong
- updated the GET /generate_name route:
- added `await` to the `isBasketUnique` line as discussed 
uitls:
- added `addNewBasket` function
- adds row to baskets table
- throws error if row not added

Add new basket

---

backend/src/routes/api.ts

Added adddtional line to check if the basket does not exist

fix: fixed basket name validation

---

frontend/src/theme.ts

got rid of the purple secondary

CHORE: theme update

---

backend/src/controllers/postgresql.ts
backend/src/main.ts
backend/src/routes/api.ts
backend/src/routes/hook.ts
backend/src/types.ts
backend/src/utils.ts

- Create a postgres class
- Move all functions from utils to the class
- Refactor logic to use the class

Postgresql class

---

backend/src/controllers/postgresql.ts
backend/src/routes/api.ts

backend/src/controllers/postgresql.ts
- added fetchBasketContents method to controller
backend/src/routes/api.ts
- added /baskets/:name/requests

added end point to get all data

---

backend/src/controllers/mongo.ts
backend/src/controllers/postgresql.ts
backend/src/routes/api.ts

- Delete all documents in the requestBody collection associated to the basket to be deleted in MongoDB
- Once the deletion in MongoDB is successful delete requests associated to the basket in PostgreSQL
Respond with:
- If deletion successful: 204 No Content
- If no basket found: 404 Not Found
Also, added better description to some log messages

Delete basket requests

---

backend/src/routes/api.ts

changed the key  for the request body.
realised the mongo connection was left open so closed it too

chore: changed request Body key

---

backend/src/controllers/mongo.ts
backend/src/controllers/postgresql.ts
backend/src/main.ts
backend/src/routes/api.ts
backend/src/routes/hook.ts

and remove success logs to keep terminal clean

FIX: Use persistent connection through the application 

---

frontend/src/App.tsx
frontend/src/components/Basket/Basket.tsx
frontend/src/components/CreateBasket/CreateBasket.tsx
frontend/src/components/StyledJSONTree/StyledJSONTree.tsx
frontend/src/theme.ts

- JSON tree bg is now just transparent
- "dark" mode
- "paper" is roughly 30% transparent and blurs bg

Feat: UI update

---

backend/src/controllers/mongo.ts
backend/src/controllers/postgresql.ts
backend/src/main.ts

Updated to use environment variables
note: it preloads the enviroment variables so no need to add them during instantiation of the pool so I updated the pool accordingly

added enviro variables

---

backend/src/routes/api.ts

- corrected status codes
- changed "/generate_token" to "baskets/generate_token"
- changed /generate_name" to "/baskets/generate_name"

fix!: fixed status codes

---

backend/src/controllers/postgresql.ts
backend/src/routes/api.ts

backend/src/routes/api.ts
- added GET  "/baskets/validate" end point 
backend/src/controllers/postgresql.ts
- added "Connected to PostgreSQL server" log on connection
- added getValidBaskets

feat: added validate names route

---

.gitignore
frontend/src/services/requestBinAPI.ts

Update requestBinAPI.ts (apiService) to send requests to new api endpoints for generate_token and generate_name

CHORE: Update requestBinAPI

---

.gitignore
frontend/src/components/Basket/Basket.tsx
frontend/src/components/Dialog/Dialog.tsx
frontend/src/components/EmptyBasketContent/EmptyBasketContent.tsx
frontend/src/components/Nav/Nav.tsx
frontend/src/components/Request/Request.tsx
frontend/src/components/RequestList/RequestList.tsx

Dynamic resizing based on screen width breakpoints at a very good place.
- Refactored request list with Grid component.
- Refactored buttons into a toolbar using ButtonGroup
- Refactored toolbar with Grid component.

Basket UI fix

---

frontend/src/services/requestBinAPI.ts

Created api service route for validating basket names

Baskets validation api

---

frontend/src/App.tsx
frontend/src/components/MyBasketsFab/MyBasketsFab.tsx

Fab now slides out to the right, so it isn't visible behind the my baskets drawer.

FIX: Fab animation

---

frontend/src/components/Basket/Basket.tsx

- I don't have time to implement a styled useDialog hook right now, and reusing the existing Dialog component twice is a bit of code smell, so taking this confirm out for now since it's not super necessary.

CHORE: Removed the window.confirm for clearing baskets

---

frontend/src/App.tsx
frontend/src/components/Basket/Basket.tsx
frontend/src/components/EmptyBasketContent/EmptyBasketContent.tsx
frontend/src/components/Nav/Nav.tsx
frontend/src/components/Request/Request.tsx
frontend/src/components/RequestList/RequestList.tsx

MOBILE SCALING ISSUES FIXED!!!

Mobile scaling

---

backend/pgDatabaseInit.ts
backend/schema.sql
backend/src/types.ts

schema.sql
- Updated create table queries to check for existing table 
backend/pgDatabaseInit.ts
- Added new file to handle Postgres DB setup via JS
- The file parses schema.sql, maintaining single source of truth
- may require more error handling and logging?

Scratchpad db automation

---

README.md

FEAT: Update README.md

---

frontend/src/components/Basket/Basket.tsx
frontend/src/components/Request/Request.tsx
frontend/src/components/StyledJSONTree/StyledJSONTree.tsx

Visual changes - fixes: #162, #147

Visual fixes

---

README.md
backend/package.json

Run `npm run nginx` to copy `dist/` to `/var/www/requestbin`.
`dist/` should be built with `npm run build` or `npm run build:frontend` first.

FEAT: Added nginx command
